groups/urls.py
from django.urls import path
from groups import views 

app_name = 'groups'

urlpatterns = [
    path('new/',views.GroupCreateView.as_view(),name='create_group'),
    path('edit/<int:pk>/<slug:slug>/',views.GroupUpdateView.as_view(),name='edit_group'),
    path('delete/<int:pk>/<slug:slug>/',views.GroupDeleteView.as_view(),name='delete_group'),
    path('<int:pk>/<slug:slug>/',views.GroupDetailView.as_view(),name='group_details'),
    path('',views.GroupListView.as_view(),name='group_list'),
    path('join/<int:pk>/<slug:slug>/',views.JoinGoup.as_view(),name='join_group'),
    path('leave/<int:pk>/<slug:slug>/',views.LeaveGoup.as_view(),name='leave_group'),
]

posts/urls.py
from django.conf.urls import url
from django.urls import path
from posts import views

app_name = 'post'

urlpatterns = [
    path('new/<int:pk>/<slug:group>',views.PostCreateView.as_view(),name='new_post'),
    path('<int:pk>/',views.PostDetailView.as_view(),name='post_details'),
    path('post_edit/<int:pk>/',views.PostUpdateView.as_view(),name='edit_post'),
    path('post_delete/<int:pk>/',views.PostDeleteView.as_view(),name='delete_post'),
    path('new_comment/<int:post>/',views.CommentCreateView.as_view(),name='new_comment'),
    path('comment_edit/<int:pk>/',views.CommentUpdateView.as_view(),name='edit_comment'),
    path('comment_delete/<int:pk>/',views.CommentDeleteView.as_view(),name='delete_comment'),
]

socialwebsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from groups import views as groups_view

urlpatterns = [
    path('',groups_view.IndexView.as_view(),name='index'),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls",namespace='accounts')),
    path("groups/"  , include("groups.urls"  ,namespace='groups')),
    path("posts/"   , include("posts.urls"   ,namespace='post')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groups/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.text import slugify
import misaka
# Create your models here.


class Group(models.Model):

    name   = models.CharField(max_length=250,unique=True)
    member = models.ManyToManyField(User, through='Membership')
    auther = models.ForeignKey(User, related_name='auther',on_delete=models.CASCADE,default='')
    image  = models.ImageField(upload_to='groups', blank=True)
    description = models.TextField(blank=True,default='')
    description_html = models.TextField(editable=False,blank=True,default='')    
    created_at = models.DateField(auto_now_add=True)    
    slug   = models.SlugField(max_length=250,unique=True,allow_unicode=True)

    def save(self,*args, **kwargs):
        self.slug   = slugify(self.name) 
        self.description_html = misaka.html(self.description)
        
        super().save(*args, **kwargs) 

    class Meta:
        ordering = ["name"]


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("groups:group_details", kwargs={"pk":self.pk,"slug": self.slug})


class Membership(models.Model):
    group = models.ForeignKey("Group", related_name='group_members', on_delete=models.CASCADE)
    user  = models.ForeignKey(User , related_name='user_groups'  , on_delete=models.CASCADE) 

    class Meta:
        unique_together = ("group", "user")


   

groups/forms.py
from django import forms
from groups.models import Group



class GroupForm(forms.ModelForm):
    
    class Meta:
        model = Group
        fields = ("name","description","image")

groups/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib import messages
from django.db import IntegrityError
from django.views import generic 
from django.shortcuts import get_object_or_404
from groups.models import Group,Membership
from groups.forms import GroupForm
# Create your views here.


class IndexView(generic.TemplateView):
    template_name = "index.html"


class GroupCreateView(generic.CreateView):
    model = Group
    form_class = GroupForm
    template_name = "groups/group_form.html"

    def form_valid(self, form):
        form.instance.auther = self.request.user
        return super().form_valid(form)   

class GroupUpdateView(generic.UpdateView):
    model = Group
    form_class = GroupForm
    template_name = "groups/group_form.html"

class GroupListView(generic.ListView):
    model = Group
    template_name = "groups/group_list.html"

class GroupDetailView(generic.DetailView):
    model = Group
    template_name = "groups/group_details.html"

class GroupDeleteView(generic.DeleteView):
    model = Group
    template_name = "groups/group_delete.html"
    success_url   = reverse_lazy("groups:group_list")

class JoinGoup(generic.RedirectView):
    pattern_name = 'groups:group_details'
    def get_redirect_url(self, *args, **kwargs):
        group = get_object_or_404(Group,pk=self.kwargs.get('pk'),slug=self.kwargs.get('slug'))
        try:
            Membership.objects.create(user=self.request.user,group=group)
        except IntegrityError:
            messages.warning(self.request,"Warning already amember of {}".format(group.name))
        else:
            messages.success(self.request,"You have successfully joined {} group".format(group.name))

        return super().get_redirect_url(*args, **kwargs)

class LeaveGoup(generic.RedirectView):
    pattern_name = 'groups:group_details'
    
    def get_redirect_url(self, *args, **kwargs):
        try:
            membership = Membership.objects.filter( user=self.request.user,group__slug=self.kwargs.get("slug")).get()
        except IntegrityError:
            messages.warning(self.request,"You are not a member of {} group".format(membership.group.name))
        else:
            membership.delete()
            messages.success(self.request,"You are no longer a member of {} group".format(membership.group.name))

        return super().get_redirect_url(*args, **kwargs)

        
    

groups/templates/groups/group_base.html
{% extends 'base.html' %}

{% block body_block %}

{% block pregroup %}{% endblock %} 
{% block group_content %}{% endblock %} 
{% block postgroup %}{% endblock %}


{% endblock %}

groups/templates/groups/group_delete.html
{% block header_block %}
<title>Group delete confirmation</title>
{% endblock header_block %}

{% block body_block %}
    <br>
    <br>
    <br>

    <form method="POST" id='myForm'>{% csrf_token %}</form>

    <script type="text/javascript">
    window.onload = function() {
    document.getElementById("myForm").submit();
    }
    </script>

{% endblock %}

groups/templates/groups/group_details.html
{% extends 'groups/group_base.html' %}
{% load static %}
{% block header_block %}
<title>Group details</title>
<link rel="stylesheet" href="{% static 'css/posts/posts.css' %}">
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css"/>
{% endblock header_block %}


{% block pregroup %}
{% endblock %}

{% block group_content %}

<div class='jumbotron'>

    {% if messages %}
        <div class="row d-flex justify-content-center">
            <div class="col-sm-6 col-sm-offset-3">
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    <p class='d-flex justify-content-center'>{{ message }}</p>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
    
    <h1 class="display-4 d-flex justify-content-center">{{group.name|safe|linebreaks}}</h1>

    {% if group.image %}
        <img src= "{{group.image.url}}" class="img-fluid rounded mx-auto d-block" alt="{{group.title}}" height="500"  style="max-width: 80%;" > 
    {% else %}    
        <img src= "{% static 'images/group_blank.jpg' %}" class="img-fluid rounded mx-auto d-block" alt="{{group.title}}" height="500"  style="max-width: 80%;" > 
    {% endif %}
    
    <br>
    <div class="d-flex d-flex justify-content-between">
        <div class="lead p-2"><small class="text-muted">@{{group.auther}}</small></div>
        <div class="lead p-2"><small class="text-muted">{{group.created_at|date:"D d M Y" }}</small></div>
    </div>
    <hr>

    <p><b>Description</b></p>
    <p> {{group.description|safe|linebreaks}}</p>  

</div>

{% if user.is_authenticated %}
    {% if user in group.member.all %}
        <a class="btn btn-danger btn-sm" href="{% url 'groups:leave_group' pk=group.pk slug=group.slug %}" role="button"><i class="fa fa-window-close" aria-hidden="true"></i> leave</a>
    {% else %}
        <a class="btn btn-primary btn-sm" href="{% url 'groups:join_group' pk=group.pk slug=group.slug %}" role="button"><i class="fa fa-plus-square" aria-hidden="true"></i> Join</a>
    {% endif %}    
    {% if user == group.auther %}
        <a class="float-right btn btn-outline-secondary btn-sm" href="{% url 'groups:edit_group' pk=group.pk slug=group.slug %}" role="button"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</a>
                    
        <!-- Button trigger modal -->
            <a class="float-right btn btn-outline-danger btn-sm" role="button" data-toggle="modal" data-target="#exampleModalCenter"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</a>
        <!-- Modal -->
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Group delete confirmation</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>are you sure you want to delete group</p>
                    </div>
                    <div class="modal-footer">
                        <a role="button" class="btn btn-secondary" data-dismiss="modal">Close</a>
                        <a role="button" class="btn btn-danger" href="{% url 'groups:delete_group' pk=group.pk slug=group.slug %}">Delete</a>
                    </div>
                </div>
            </div>
        </div> 
    {% endif %}
{% endif %}

<br><br>

<hr>


{% include 'post/_post_list.html'  %}


{% endblock  %}

groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}

{% load bootstrap4 %}


{% block group_content %}

{% if  not form.instance.pk %}
    <h1>Create new group</h1>
{% else %}
    <h1>Update group</h1>
{% endif %}

<br><br>

<form method="POST" enctype="multipart/form-data">{% csrf_token %}

{% bootstrap_form form %}
<br><br>
        
<input type="submit" class="btn btn-primary sm-btn" value="Submit">


</form>

{% endblock  %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}
{% load static %}
{% block header_block %}
<link rel="stylesheet" type="text/css" href="{% static 'css/groups/groups.css' %}">
<title>Groups</title>
{% endblock header_block %}

{% block group_content %}

<div class='jumbotron'>
<h1 class='display-4 text-center'>Groups</h1>
</div>

<div class='container'>
    <div class='group_list'>
    <div class="row justify-content-left">   
        {% for group in group_list %}
            <div class="card m-4" style="width: 18rem;">
                
                <a href="{% url 'groups:group_details' pk=group.pk slug=group.slug %}">
                {% if  group.image %}
                    <img class="card-img-top " src="{{group.image.url}}" alt='{{group.name}}' height="180">
                {% else %}
                    <img class="card-img-top" src="{% static 'images/group_blank.jpg' %}" alt='{{group.name}}' height="180">
                {% endif %}
                </a>
                    
                <div class="card-body">
                    <small class="text-muted  float-right">
                        <span class="badge badge-secondary">{{ group.member.count }}</span> member{{ group.member.count|pluralize }}
                        <span class="badge badge-secondary">{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}
                    </small>
                    <h5 class="card-title">{{group.name}}</h5>
                    {% comment %} <h5 class="card-title float-right">{{group.name}}</h5> {% endcomment %}
                    

                    <p class="card-text">{{group.description|slice:":25" }} {% if group.description|length >= 25 %}....{% endif %}</p>
                    

                    {% if user.is_authenticated %}
                        {% if user in group.member.all %}
                            <a class="btn btn-danger btn-sm" href="{% url 'groups:leave_group' pk=group.pk slug=group.slug %}" role="button"><i class="fa fa-window-close" aria-hidden="true"></i> leave</a>
                        {% else %}
                            <a class="btn btn-primary btn-sm" href="{% url 'groups:join_group' pk=group.pk slug=group.slug %}" role="button"><i class="fa fa-plus-square" aria-hidden="true"></i> Join</a>
                        {% endif %}

                        {% if user == group.auther %}
                            <a class="float-right btn btn-outline-secondary btn-sm" href="{% url 'groups:edit_group' pk=group.pk slug=group.slug %}" role="button"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</a>
                
                            <!-- Button trigger modal -->
                                <a class="float-right btn btn-outline-danger btn-sm" role="button" data-toggle="modal" data-target="#exampleModalCenter"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</a>
                            <!-- Modal -->
                            <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLongTitle">Group delete confirmation</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <p>are you sure you want to delete group</p>
                                        </div>
                                        <div class="modal-footer">
                                            <a role="button" class="btn btn-secondary" data-dismiss="modal">Close</a>
                                            <a role="button" class="btn btn-danger" href="{% url 'groups:delete_group' pk=group.pk slug=group.slug %}">Delete</a>
                                        </div>
                                    </div>
                                </div>
                            </div> 
                        {% endif %}    
                    {% endif %}
                    
                </div>
            </div>
            <br><br>

        {% endfor %}
    </div>    
    </div>
</div>    



{% endblock  %}