accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views,forms
from django.urls import reverse_lazy


app_name = 'accounts'

urlpatterns = [
    path('login/', 
        auth_views.LoginView.as_view(template_name='accounts/login.html'),
        name='login'
        ),
    path('logout/', 
        auth_views.LogoutView.as_view(template_name='accounts/logout.html'),
        name='logout'
        ),
    path('signup/', 
        views.SignCreateView.as_view(),
        name='signup'
        ),
    path('password_change/', 
        auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'
                                            ,success_url=reverse_lazy('accounts:password_change_done')),
        name='password_change',                                    
        ),
    path('password_change/done/', 
        auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
        name='password_change_done'
        ),
    path('password_reset/', 
        auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'
                                            ,email_template_name='accounts/password_reset_email.html'
                                            ,success_url=reverse_lazy('accounts:password_reset_done')),
        name='password_reset',
        ),
    path('password_reset/done/', 
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'
        ),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
                                                    success_url=reverse_lazy('accounts:password_reset_complete')),
        name='password_reset_confirm',
        ),
    path('password_reset_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete',
        ),    
    

]

posts/urls.py
from django.conf.urls import url
from django.urls import path
from posts import views

app_name = 'post'

urlpatterns = [
    path('new/<int:pk>/<slug:group>',views.PostCreateView.as_view(),name='new_post'),
    path('<int:pk>/',views.PostDetailView.as_view(),name='post_details'),
    path('post_edit/<int:pk>/',views.PostUpdateView.as_view(),name='edit_post'),
    path('post_delete/<int:pk>/',views.PostDeleteView.as_view(),name='delete_post'),
    path('new_comment/<int:post>/',views.CommentCreateView.as_view(),name='new_comment'),
    path('comment_edit/<int:pk>/',views.CommentUpdateView.as_view(),name='edit_comment'),
    path('comment_delete/<int:pk>/',views.CommentDeleteView.as_view(),name='delete_comment'),
]

socialwebsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from groups import views as groups_view

urlpatterns = [
    path('',groups_view.IndexView.as_view(),name='index'),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls",namespace='accounts')),
    path("groups/"  , include("groups.urls"  ,namespace='groups')),
    path("posts/"   , include("posts.urls"   ,namespace='post')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    title      = models.CharField(max_length=250)
    body       = models.TextField()
    auther     = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateField(auto_now_add=True)
    image        = models.ImageField(upload_to='post_pics', blank=True)
    group      = models.ForeignKey("groups.Group",related_name='posts', on_delete=models.CASCADE)
    

    class Meta:
        ordering=('created_at',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post:post_details", kwargs={"pk": self.pk})



class Comment(models.Model):
    post   = models.ForeignKey("posts.Post",related_name='comments' ,on_delete=models.CASCADE)
    auther = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    text   = models.TextField() 
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.text
    
    def get_absolute_url(self):
        return reverse("post:post_details", kwargs={"pk": self.post.id})

posts/forms.py
from django import forms
from posts.models import Post,Comment

class PostForm(forms.ModelForm):
    class Meta:
        model  = Post
        fields = ("title","body","image")
        widgets = {
            'title':forms.TextInput(attrs={'class':'editable'}),
            'body' :forms.Textarea( attrs={'class':'editable medium-editor-textarea',
                                           'style':'overflow:auto;resize:none;height:100px;'}),
        } 
    
    

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('text',)

        widgets = {
            'text' :forms.Textarea(attrs={'class':'editable medium-editor-textarea',
                                          'style':'overflow:auto;resize:none;height:100px;'}),
        } 

posts/views.py
from django.shortcuts import render
from django.views import generic
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from groups.models import Group
from posts.models import Post,Comment
from posts.forms import PostForm,CommentForm
# Create your views here.

class PostCreateView(LoginRequiredMixin,generic.CreateView):
    login_url = '/accounts/login/'
    model      = Post
    form_class = PostForm

    template_name = "post/post_form.html"

    def form_valid(self, form):
        form.instance.auther = self.request.user
        form.instance.group  = get_object_or_404(Group,slug=self.kwargs['group'])
        return super().form_valid(form)   

class PostUpdateView(LoginRequiredMixin,generic.UpdateView):
    login_url = '/accounts/login/'
    model      = Post
    form_class = PostForm

    template_name = "post/post_form.html"    

class PostDeleteView(LoginRequiredMixin,generic.DeleteView):
    login_url = '/accounts/login/'
    model      = Post
    success_url = reverse_lazy("post:posts")
    template_name = "post/post_delete.html"

class PostDetailView(generic.DetailView):
    model = Post
    template_name = "post/post_detail.html"


class CommentCreateView(LoginRequiredMixin,generic.CreateView):
    login_url = '/accounts/login/'
    model      = Comment
    form_class = CommentForm

    template_name = "post/comment_form.html"

    def form_valid(self, form):
        form.instance.auther = self.request.user
        form.instance.post   = get_object_or_404(Post,pk=self.kwargs['post']) 
        return super().form_valid(form)


class CommentUpdateView(LoginRequiredMixin,generic.UpdateView):
    login_url = '/accounts/login/'
    model      = Comment
    form_class = CommentForm

    template_name = "post/comment_form.html"    

class CommentDeleteView(LoginRequiredMixin,generic.DeleteView):
    login_url = '/accounts/login/'
    model      = Comment
    template_name = "post/comment_delete.html"

    def get_success_url(self):
        comment    = get_object_or_404(Comment,pk=self.kwargs.get('pk'))
        return reverse_lazy("post:post_detail", kwargs={'pk': comment.post.pk})

posts/templates/post/_post_list.html
{% load static %}
{% if user.is_authenticated %}
    {% if user in group.member.all %}
        {% comment %} creat new post {% endcomment %}
        <a class="btn btn-primary btn-sm" href="{% url 'post:new_post' pk=group.pk group=group.slug %}" role="button"><i class="fa fa-plus-square" aria-hidden="true"></i> Create post</a>
        <br><br><br>
        <div class="row justify-content-left">   
            {% for post in group.posts.all %}
               <div class="well">
                    <div class="media">
                        <a class='pull-left' href="{% url 'post:post_details' pk=post.pk %}">
                            {% if  post.image %}
                                <img class="media-object mx-3 img-thumbnail" src="{{post.image.url}}" alt="{% static 'images/post/post_blank.png' %}" width="150" height="150">
                            {% else %}
                                <img class="media-object mx-3 img-thumbnail" src="{% static 'images/post/post_blank.png' %}" alt='{{group.name|safe|linebreaks}}' width="150" height="150">
                            {% endif %}
                        </a>
                        <div class="media-body">
                            <p class="float-right">By {{post.auther}}</p>
                            <h4 class="media-heading">{{post.title|safe}}</h4>
                            <p>{{post.body| striptags | safe | escape}}</p>
                            <ul class="list-inline list-unstyled">
                                <li class='list-inline-item'><span><i class="fa fa-calendar" aria-hidden="true"></i> {{post.created_at|date:"D d M Y"}} </span></li>
                                <li class='list-inline-item'>|</li>
                                <span><i class="fa fa-comment" aria-hidden="true"></i><span> {{ post.comments.count }}</span>  comment{{ post.comments.count|pluralize }}</span>
                                <li class='list-inline-item'>|</li>
                                <li class='list-inline-item'>
                                <span><i class="fa fa-facebook-square"></i></span>
                                <span><i class="fa fa-twitter-square"></i></span>
                                <span><i class="fa fa-google-plus-square"></i></span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <hr>

            {% endfor %}
        </div> 
    {% else %}   
    <p>join group to see group posts</p>
    {% endif %}
{% else %}
    <p><a href="{% url 'accounts:login' %}">Login</a> to see group posts</p>
{% endif %}

<br><br>

posts/templates/post/comment_delete.html
{% extends 'base.html' %}



{% if user.is_authenticated %}

    {% block header_block %}
    <title>Comment delete confirmation</title>
    {% endblock header_block %}

    {% block body_block %}
        <br>
        <br>
        <br>

        <form method="POST" id='myForm'>{% csrf_token %}
        <input type="hidden" value="submit">
        </form>

        <script type="text/javascript">
        window.onload = function() {
        document.getElementById("myForm").submit();
        }
        </script>

    {% endblock %}




{% else %}
    Not allowed please login
{% endif %}

posts/templates/post/comment_form.html
{% extends 'base.html' %}
{%load bootstrap4%}
{% block header_block %}
<title>Comment form</title>
{% endblock header_block %}

{% block body_block %}
<div class="jumbotron">
   
    {% if  not form.instance.pk %}
        <h1>Create new comment</h1>
    {% else %}
        <h1>Update comment</h1>
    {% endif %}
    
    <br><br>
    

    <form method="POST">{% csrf_token %}
        {% bootstrap_form form %}
        <br><br>

        <input type="submit" class="btn btn-primary sm-btn" value="Submit">
    </form>
</div>
{% endblock body_block %}

posts/templates/post/post_delete.html
{% extends 'base.html' %}



{% if user.is_authenticated %}

    {% block header_block %}
    <title>Post delete confirmation</title>
    {% endblock header_block %}

    {% block body_block %}
        <br>
        <br>
        <br>

        <form method="POST" id='myForm'>{% csrf_token %}</form>

        <script type="text/javascript">
        window.onload = function() {
        document.getElementById("myForm").submit();
        }
        </script>

    {% endblock %}




{% else %}
    Not allowed please login
{% endif %}

posts/templates/post/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block header_block %}
<title>Post details</title>
<link rel="stylesheet" href="{% static 'css/posts/comment_section.css' %}">

{% endblock header_block %}

{% block body_block %}

    {% if post.published_at or user.is_authenticated %}
        <div class='jumbotron'>

            <h1 class="d-flex justify-content-center">{{post.title|safe|linebreaks}}</h1>

            {% if post.image %}
                    <img src= "{{post.image.url}}" class="img-fluid rounded mx-auto d-block" alt="{{post.title}}" height="500"  style="max-width: 80%;" > 
            {% endif %}
            
            <br>
            <br>
            
            <div class="d-flex d-flex justify-content-between">
                <div class="lead p-2"><small class="text-muted">@{{post.auther}}</small></div>
                <div class="lead p-2"><small class="text-muted">{{post.created_at|date:"D d M Y" }}</small></div>
            </div>
            <hr>    
        </div>

        
        <br>
        <br>
        

        <p> {{post.body|safe|linebreaks}}</p>
        
        <br>
        <br>
        {% if user.is_authenticated %}
            <a class="btn btn-primary btn-sm" href="{% url 'post:edit_post' post.pk %}" role="button"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</a>
            <!-- Button trigger modal -->
                <a class="btn btn-danger btn-sm" role="button" data-toggle="modal" data-target="#exampleModalCenter"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</a>
            <!-- Modal -->
            <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLongTitle">Post delete confirmation</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>are you sure you want to delete post</p>
                        </div>
                        <div class="modal-footer">
                            <a role="button" class="btn btn-secondary" data-dismiss="modal">Close</a>
                            <a role="button" class="btn btn-danger" href="{% url 'post:delete_post' post.pk %}">Delete</a>
                        </div>
                    </div>
                </div>
            </div> 
        
        {% endif %}      
        <br>
        <br>
        <hr>
        <h2>Comments</h2>                                                                
        <br>

        {% for comment in post.comments.all %}
            <div class="d-flex justify-content-left py-2">
                <div class="second py-2 px-2"> 
                    <div class="d-flex flex-column justify-content-between">
                        
                        <div class="p-2 d-flex flex-row justify-content-between">
                            <div>
                                <img src="{% static 'images/post/user-anonymous.png' %}" width="18">
                                <span class="text2">{{comment.auther}}</span>
                            </div>
                            <span class="text3">{{comment.created_at|date:"D d M Y"}}</span>
                        </div>
                    
                        <div class="p-2">
                            <span class="text1 p-2">{{comment.text|safe|linebreaks}}</span>
                        </div>    
                        <div class="p-2">
                            {% if user.is_authenticated %}
                                <a class="btn btn-primary btn-sm float-right ml-1" href="{% url 'post:edit_comment' comment.pk  %}" role="button"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</a>
                                
                                <!-- Button trigger modal -->
                                <a class="btn btn-danger btn-sm float-right" role="button" data-toggle="modal" data-target="#exampleModalCenter1"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</a>  

                                <!-- Modal -->
                                <div class="modal fade" id="exampleModalCenter1" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLongTitle">Comment delete confirmation</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <p>are you sure you want to delete comment</p>
                                            </div>
                                            <div class="modal-footer">
                                                <a role="button" class="btn btn-secondary" data-dismiss="modal">Close</a>
                                                <a role="button" class="btn btn-danger" href="{% url 'post:delete_comment' comment.pk  %}">Delete</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>  
                            {% endif %}                              
                        </div>                        
                    </div>
                </div>
            </div>
            
        {% endfor %}
        <br><br>
        {% if user.is_authenticated %}
        <a class="btn btn-primary btn-sm" href="{% url 'post:new_comment' post=post.pk %}" role="button"><i class="fa fa-plus-square" aria-hidden="true"></i> add comment</a>
        {% endif %}
        <br><br><br>


    {% else %}
        <h1>Not allowed please login</h1>
    {% endif %}       
{% endblock %}

posts/templates/post/post_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block header_block %}
<title>Post form</title>
{% endblock header_block %}

{% block body_block %}
<div class="jumbotron">

        {% if  not form.instance.pk %}
            <h1>Create new post</h1>
        {% else %}
            <h1>Update post</h1>
        {% endif %}
    
    <br><br>
    

    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
    
        {% bootstrap_form form %}
        
        <br><br>
        
        <input type="submit" class="btn btn-primary sm-btn" value="Submit">
        
    </form>
</div>
{% endblock body_block %}