accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views,forms
from django.urls import reverse_lazy


app_name = 'accounts'

urlpatterns = [
    path('login/', 
        auth_views.LoginView.as_view(template_name='accounts/login.html'),
        name='login'
        ),
    path('logout/', 
        auth_views.LogoutView.as_view(template_name='accounts/logout.html'),
        name='logout'
        ),
    path('signup/', 
        views.SignCreateView.as_view(),
        name='signup'
        ),
    path('password_change/', 
        auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'
                                            ,success_url=reverse_lazy('accounts:password_change_done')),
        name='password_change',                                    
        ),
    path('password_change/done/', 
        auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
        name='password_change_done'
        ),
    path('password_reset/', 
        auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'
                                            ,email_template_name='accounts/password_reset_email.html'
                                            ,success_url=reverse_lazy('accounts:password_reset_done')),
        name='password_reset',
        ),
    path('password_reset/done/', 
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'
        ),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
                                                    success_url=reverse_lazy('accounts:password_reset_complete')),
        name='password_reset_confirm',
        ),
    path('password_reset_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete',
        ),    
    

]

posts/urls.py
from django.conf.urls import url
from django.urls import path
from posts import views

app_name = 'post'

urlpatterns = [
    path('new/<int:pk>/<slug:group>',views.PostCreateView.as_view(),name='new_post'),
    path('<int:pk>/',views.PostDetailView.as_view(),name='post_details'),
    path('post_edit/<int:pk>/',views.PostUpdateView.as_view(),name='edit_post'),
    path('post_delete/<int:pk>/',views.PostDeleteView.as_view(),name='delete_post'),
    path('new_comment/<int:post>/',views.CommentCreateView.as_view(),name='new_comment'),
    path('comment_edit/<int:pk>/',views.CommentUpdateView.as_view(),name='edit_comment'),
    path('comment_delete/<int:pk>/',views.CommentDeleteView.as_view(),name='delete_comment'),
]

socialwebsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from groups import views as groups_view

urlpatterns = [
    path('',groups_view.IndexView.as_view(),name='index'),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls",namespace='accounts')),
    path("groups/"  , include("groups.urls"  ,namespace='groups')),
    path("posts/"   , include("posts.urls"   ,namespace='post')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.




   

accounts/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django import forms

class UserCreateForm(UserCreationForm):
    
    class Meta:
        model  = User 
        fields = ('first_name','last_name','username','email','password1','password2')
        
        widgets = {
            'username':forms.TextInput(attrs={ 'placeholder':'User Name'}),
            'email':forms.EmailInput(attrs={ 'placeholder':'Email Adress'}),
           
        } 

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView,TemplateView
from django.urls import reverse_lazy
from . import forms




class SignCreateView(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('accounts:login')
    template_name = "accounts/signup.html"

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block header_block %}
<title>Login</title>
{% endblock header_block %}

{% block body_block %}

<br><br><br>

<div class='container'>
    <div class='row justify-content-center align-items-center'>
    <aside class="col-sm-4 ">
        <div class="card">
            <article class="card-body">
                <a href="{% url 'accounts:signup' %}" class="float-right btn btn-outline-primary">Sign up</a>
                <h4 class="card-title text-left mb-4 mt-1">Sign in</h4>
                <hr>
                <p class="text-success text-center">please enter email and password</p>

                {% if form.errors %}
                    <p class='text-center'>Your username and password didn't match. Please try again.</p>
                {% endif %}

                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"> <i class="fa fa-user"></i> </span>        
                            </div>
                            <input for='id_username' name='username' class="form-control" placeholder="User Name" type="text">
                        </div> <!-- input-group.// -->
                    </div> <!-- form-group// -->

                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                            </div>
                            <input for='id_password' name='password' class="form-control" placeholder="**********" type="password">
                        </div> <!-- input-group.// -->
                    </div> <!-- form-group// -->

                    <br>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Login  </button>
                        <input type="hidden" name="next" value="{{ next }}" />
                    </div> <!-- form-group// -->
                    <p class="text-center"><a href="{% url 'accounts:password_reset' %}">Forgot password?</a></p>
                </form>
            </article>
        </div> <!-- card.// -->
    </aside> <!-- col.// -->
    </div>
</div> <!--container end.//-->            



<br><br><br>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block header_block %}
<title>Logout</title>
{% endblock header_block %}


{% block body_block %}
  <div class='jumbotron'>
    <h1>Logged out!</h1>
    <a href="{% url 'accounts:login'%}">Click here to login again.</a>
  </div>
{% endblock %}

accounts/templates/accounts/password_change.html
{% extends "base.html" %}
{%load bootstrap4%}
{% block body_block %}
        <div class='jumbotron'>
        <h1>Please enter (and confirm) your new password.</h1>
        
        
        <form action="" method="post">
        {% csrf_token %}
            
            {% bootstrap_form form %}

            <input type='submit' class='btn btn-primary' value='Change password'>
        </form>
   
    </div>
{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends "base.html" %}

{% block body_block %}
  <div class='jumbotron'>
    <h1>The password has been changed!</h1>
    <br>
    <p><a href="{% url 'accounts:login' %}">log in again?</a></p>
  </div>  
{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends "base.html" %}

{% block body_block %}
  
  <div class='jumbotron'>
    <div class="d-flex justify-content-center">
      <div class="d-flex flex-column bd-highlight mb-3">
        <div class="p-2 bd-highlight"><h3>Please inter the email youy registered with<h3></div>
        <div class="p-2 bd-highlight d-flex justify-content-center">        
          <form method="post">{% csrf_token %}
          
            {% if form.email.errors %}
                {{ form.email.errors }}
            {% endif %}
            
            <p>{{ form.email }}</p>
            
            <input type="submit" class="btn btn-primary btn-lg rounded-pill d-flex justify-content-center" value="Reset password">
        
          </form>
        </div>
        
      </div>
    </div>
  </div>  
  
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}

{% block body_block %}
  <div class='jumbotron'>
    <h1>The password has been changed!</h1>
    <br>
    <p><a href="{% url 'accounts:login' %}">log in again?</a></p>
  </div>  
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{%load bootstrap4%}
{% block body_block %}
    {% if validlink %}
        <div class='jumbotron'>
        <h1>Please enter (and confirm) your new password.</h1>
        
        
        <form action="" method="post">
        {% csrf_token %}
            
            {% bootstrap_form form %}

            <input type='submit' class='btn btn-primary' value='Change password'>
        </form>
    {% else %}
        <h1>Password reset failed</h1>
        <p>The password reset link was invalid, possibly because it has already been used. Please request a new password reset.</p>
    {% endif %}
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block header_block %}<title>Email Sent</title>{% endblock %}

{% block body_block %}
<div class='jumbotron'>
  <h1>Check your inbox.</h1>
  <p>We've emailed you instructions for setting your password. You should receive the email shortly!</p>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block header_block %}
<title>SignUp</title>
{% endblock header_block %}


{% block body_block %}
  <h1>SignUp</h1>
  <form method='POST'>{% csrf_token %}

  {% bootstrap_form form %}
  
  <input type='submit' class='btn btn-primary' value='Sign Up'>
  
  </form>


{% endblock %}