accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views,forms
from django.urls import reverse_lazy


app_name = 'accounts'

urlpatterns = [
    path('login/', 
        auth_views.LoginView.as_view(template_name='accounts/login.html'),
        name='login'
        ),
    path('logout/', 
        auth_views.LogoutView.as_view(template_name='accounts/logout.html'),
        name='logout'
        ),
    path('signup/', 
        views.SignCreateView.as_view(),
        name='signup'
        ),
    path('password_change/', 
        auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'
                                            ,success_url=reverse_lazy('accounts:password_change_done')),
        name='password_change',                                    
        ),
    path('password_change/done/', 
        auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
        name='password_change_done'
        ),
    path('password_reset/', 
        auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'
                                            ,email_template_name='accounts/password_reset_email.html'
                                            ,success_url=reverse_lazy('accounts:password_reset_done')),
        name='password_reset',
        ),
    path('password_reset/done/', 
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'
        ),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
                                                    success_url=reverse_lazy('accounts:password_reset_complete')),
        name='password_reset_confirm',
        ),
    path('password_reset_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete',
        ),    
    

]

groups/urls.py
from django.urls import path
from groups import views 

app_name = 'groups'

urlpatterns = [
    path('new/',views.GroupCreateView.as_view(),name='create_group'),
    path('edit/<int:pk>/<slug:slug>/',views.GroupUpdateView.as_view(),name='edit_group'),
    path('delete/<int:pk>/<slug:slug>/',views.GroupDeleteView.as_view(),name='delete_group'),
    path('<int:pk>/<slug:slug>/',views.GroupDetailView.as_view(),name='group_details'),
    path('',views.GroupListView.as_view(),name='group_list'),
    path('join/<int:pk>/<slug:slug>/',views.JoinGoup.as_view(),name='join_group'),
    path('leave/<int:pk>/<slug:slug>/',views.LeaveGoup.as_view(),name='leave_group'),
]

posts/urls.py
from django.conf.urls import url
from django.urls import path
from posts import views

app_name = 'post'

urlpatterns = [
    path('new/<int:pk>/<slug:group>',views.PostCreateView.as_view(),name='new_post'),
    path('<int:pk>/',views.PostDetailView.as_view(),name='post_details'),
    path('post_edit/<int:pk>/',views.PostUpdateView.as_view(),name='edit_post'),
    path('post_delete/<int:pk>/',views.PostDeleteView.as_view(),name='delete_post'),
    path('new_comment/<int:post>/',views.CommentCreateView.as_view(),name='new_comment'),
    path('comment_edit/<int:pk>/',views.CommentUpdateView.as_view(),name='edit_comment'),
    path('comment_delete/<int:pk>/',views.CommentDeleteView.as_view(),name='delete_comment'),
]

socialwebsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from groups import views as groups_view

urlpatterns = [
    path('',groups_view.IndexView.as_view(),name='index'),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls",namespace='accounts')),
    path("groups/"  , include("groups.urls"  ,namespace='groups')),
    path("posts/"   , include("posts.urls"   ,namespace='post')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<html lang="en">

    {%load static%}

    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- bootstrap css -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
   
    <!-- medium editor -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    


    {% block header_block %}
    
    {% endblock %}
    
</head>
<body>
    
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #fad55a;" >
            <a class="navbar-brand" href="{% url 'index' %}"> <img src="{% static 'images/Razan logo.png' %}" alt="" height="30"> </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}"><b>admin</b></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'groups:group_list' %}"><b>Groups</b></a>
                </li>
              </ul>
              
               
            
              <ul class="navbar-nav ml-auto">          
                <li class="nav-link">
                    <a class="nav-link" href="{% url 'groups:create_group' %}"><b>Create Group</b></a>
                </li>
                <li class="nav-link">
                    <div class="btn-group" role="group">
                        <i id="btnGroupDrop1"  class="fa fa-user-circle-o fa-2x" data-toggle="dropdown" aria-haspopup="true"  aria-hidden="true"></i>
                        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                        <a class="dropdown-item" href="#"><b>{{user.username}}</b></a>
                        {% if user.is_authenticated %}
                            <a class="dropdown-item" href="{% url 'accounts:logout' %}"><b>logout</b></a>
                            <a class="dropdown-item" href="{% url 'accounts:password_change' %}"><b>Change password</b></a>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'accounts:login' %}"><b>login</b></a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'accounts:signup' %}"><b>register</b></a>           
                    </div>
                </li>
                <li class="nav-link">
                     
                </li>

            </div>

        </nav>

        
        
    </div>
    
    <div class="container">
    {%block body_block %}
    {% endblock body_block%}
    </div>    
        
  

    <!-- bootstrapcdn js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <!-- MediumEditorCDN -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    
    <script>
        var editor = new MediumEditor('.editable', 
            {
                toolbar: {
                /* These are the default options for the toolbar,
                if nothing is passed this is what is used */
                allowMultiParagraphSelection: true,
                buttons: ['bold', 'italic', 'underline', 'anchor', 'h1', 'h2','p', 'h3' , 'quote'],
                diffLeft: 0,
                diffTop: -10,
                firstButtonClass: 'medium-editor-button-first',
                lastButtonClass: 'medium-editor-button-last',
                relativeContainer: null,
                standardizeSelectionStart: false,
                static: false,
                /* options which only apply when static is true */
                align: 'center',
                sticky: false,
                updateOnEmptySelection: false
                }
            });
        
            editor.subscribe('editableInput', function (event, editable) {
            var x = editable.innerHTML; // editable is the editor <div> element that was changed
            var y = editor.getContent(); // getContent() returns the content of the editor as well
            console.log(x)
            console.log(y)
            });

 
    </script>

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block header_block %}
<title>Home</title>
{% endblock  %}

{% block body_block %}
  <div class="jumbotron">
      <div class="editable"><h1>Hello</h1></div>
  </div>


  <!--Carousel Wrapper-->
  <div id="carousel-example-2" class="carousel slide carousel-fade z-depth-1-half" data-ride="carousel">
      <!--Indicators-->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-2" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-2" data-slide-to="1"></li>
        <li data-target="#carousel-example-2" data-slide-to="2"></li>
      </ol>
      <!--/.Indicators-->
      <!--Slides-->
      <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
          <div class="view">
            <img class="d-block w-100" src="https://image.freepik.com/free-photo/minimalist-black-background-with-square-geometric-shapes_103577-5240.jpg" height="500" alt="First slide">
            <div class="mask rgba-black-light"></div>
          </div>
          <div class="carousel-caption">
            <h3 class="h3-responsive">This is the first title</h3>
            <p>First text</p>
          </div>
        </div>
        <div class="carousel-item">
          <!--Mask color-->
          <div class="view">
            <img class="d-block w-100" src="https://image.freepik.com/free-photo/abstract-polygonal-space-low-poly-dark-background-3d-rendering_7247-223.jpg" height="500" alt="Second slide">
            <div class="mask rgba-black-light"></div>
          </div>
          <div class="carousel-caption">
            <h3 class="h3-responsive">Thir is the second title</h3>
            <p>Secondary text</p>
          </div>
        </div>
        <div class="carousel-item">
          <!--Mask color-->
          <div class="view">
            <img class="d-block w-100" src="https://image.freepik.com/free-photo/cosmic-background-with-colorful-laser-lights-with-cool-shapes-perfect-digital-wallpaper_181624-21410.jpg" height="500" alt="Third slide">
            <div class="mask rgba-black-light"></div>
          </div>
          <div class="carousel-caption">
            <h3 class="h3-responsive">This is the third title</h3>
            <p>Third text</p>
          </div>
        </div>
      </div>
      <!--/.Slides-->
      <!--Controls-->
      <a class="carousel-control-prev" href="#carousel-example-2" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carousel-example-2" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
      <!--/.Controls-->
    </div>
    <!--/.Carousel Wrapper-->
<br><br><br>

{% endblock body_block %}